<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\Billpay;

interface BillpayConstants
{
    const GATEWAY_URL = 'BILLPAY:GATEWAY_URL';
    const IS_TEST_MODE = 'BILLPAY:IS_TEST_MODE';
    const VENDOR_ROOT = 'BILLPAY:VENDOR_ROOT';

    const BILLPAY_MERCHANT_ID = 'BILLPAY:BILLPAY_MERCHANT_ID';
    const BILLPAY_PORTAL_ID = 'BILLPAY:BILLPAY_PORTAL_ID';
    const BILLPAY_SECURITY_KEY = 'BILLPAY:BILLPAY_SECURITY_KEY';
    const BILLPAY_PUBLIC_API_KEY = 'BILLPAY:BILLPAY_PUBLIC_API_KEY';
    const BILLPAY_MAX_DELAY_IN_DAYS = 'BILLPAY:BILLPAY_MAX_DELAY_IN_DAYS';
    const USE_MD5_HASH = 'BILLPAY:USE_MD5_HASH';

    const USE_PRESCORE = 'USE_PRESCORE';

    /**
     * A list of methods
     */
    const AVAILABLE_PROVIDER_METHODS = [
        BillpayConfig::INVOICE_B2C,
    ];

    const PARAM_GROUP_CUSTOMER = 'BILLPAY:PARAM_GROUP_CUSTOMER';
    const PARAM_GROUP_SHIPPING = 'BILLPAY:PARAM_GROUP_SHIPPING';
    const PARAM_GROUP_ARTICLES = 'BILLPAY:PARAM_GROUP_ARTICLES';
    const PARAM_GROUP_TOTALS = 'BILLPAY:PARAM_GROUP_TOTALS';
    const PARAM_GROUP_PRESCORE = 'BILLPAY:PARAM_GROUP_PRESCORE';
    const PARAM_GROUP_INVOICE = 'BILLPAY:PARAM_GROUP_INVOICE';

    const PAYMENT_METHODS_MAP = [
        BillpayConfig::METHOD_INVOICE => BillpayConfig::IPL_CORE_PAYMENT_TYPE_INVOICE,
    ];

    const PARAM_GROUP_CANCEL = 'BILLPAY:PARAM_GROUP_CANCEL';
}
